# 02 — AAA section-aware chunking and local embeddings

Builds RAG chunks from the cleaned pages produced by notebook 01, validates chunk quality, then embeds only valid chunks with a local free model.

No paid embedding API is used. Chunk text is source text, not a paraphrase.

In [1]:
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

try:
    from IPython.display import display
except ImportError:
    def display(obj):
        print(obj)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 140)
pd.set_option("display.width", 180)

cwd = Path.cwd().resolve()
for candidate in [cwd, cwd.parent]:
    if (candidate / "ingestion" / "chunking.py").exists():
        sys.path.insert(0, str(candidate))
        break

import ingestion.chunking as cc
import ingestion.preprocess as cp
import retrieval.index as cr

PROJECT_ROOT = cp.find_project_root()
print("Project root:", PROJECT_ROOT)
print("Embedding model:", cr.DEFAULT_MODEL)

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.

Project root: C:\Users\DELL\Downloads\aaa-clinical-rag
Embedding model: sentence-transformers/all-MiniLM-L6-v2

## Chunking

Chunks prefer section boundaries, keep recommendations with surrounding context, and avoid splitting numeric ranges.

In [2]:
chunk_result = cc.run_chunking(PROJECT_ROOT)
cc.print_chunk_report(chunk_result["quality"])
chunks = chunk_result["chunks"]
print("\nWrote", chunk_result["relative_path"])
print("Chunks by document:")
display(pd.DataFrame(chunks).groupby(["document_id", "document_name"]).size().rename("n_chunks").to_frame())

C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1547 > 512). Running this sequence through the model will result in indexing errors

CHUNKS
- total: 2116
- valid: 2116
- invalid: 0
- duplicates: 2
- missing metadata issues: 0
- missing section_title: 530

TOKENS (tokenizer: sentence-transformers/all-MiniLM-L6-v2, limit 256)
- chunks: 2116
- min: 12
- median: 206.0
- mean: 194.78
- max: 254
- EXCEEDING_LIMIT = 0

CONTENT TYPES
- boilerplate: 14
- clinical: 1330
- reference: 661
- title_only: 8
- toc: 103

- status: PASS

Wrote data/chunks/chunks.json
Chunks by document:

                                                                                                                                                          n_chunks
document_id document_name
ESVS_2024   Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Il...      1806
NICE_NG156  Abdominal aortic aneurysm: diagnosis and management                                                                                                158
SVS_2018    Care of Patients with an Abdominal Aortic Aneurysm                                                                                                  48
USPSTF_2019 Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement                                                104

In [3]:
chunk_df = pd.DataFrame(chunks)
print("Chunk metadata sample")
display(chunk_df[["chunk_id", "document_id", "section_title", "page_start", "page_end", "content_type", "token_count", "char_count"]].head(12))

print("\nToken distribution (tokenizer of the embedding model)")
stats = chunk_result["quality"]["tokens"]
display(pd.Series(stats).to_frame("value"))

print("\nChunks by content type (low-value types are kept on disk but excluded from the index)")
display(chunk_df["content_type"].value_counts().rename("n_chunks").to_frame())

print("\nSample chunks - metadata AND the real chunk text")
cc.print_chunk_samples(chunks, per_document=2, max_chars=700)

# Hard gate: nothing may exceed the embedding model's window, because
# SentenceTransformer.encode() would silently truncate it.
assert stats["exceeding_limit"] == 0, f"{stats['exceeding_limit']} chunk(s) exceed {stats['token_limit']} tokens"
assert chunk_result["quality"]["status"] == "PASS", chunk_result["quality"]["errors"]
assert (PROJECT_ROOT / "data" / "chunks" / "chunks.json").stat().st_size > 0
print(f"\nEXCEEDING_LIMIT = {stats['exceeding_limit']}")

Chunk metadata sample

                  chunk_id document_id                         section_title  page_start  page_end content_type  token_count  char_count
0   ESVS_2024__p1-1__c0001   ESVS_2024  CLINICAL PRACTICE GUIDELINE DOCUMENT           1         1     clinical          220         696
1   ESVS_2024__p1-1__c0002   ESVS_2024  CLINICAL PRACTICE GUIDELINE DOCUMENT           1         1     clinical          206         754
2   ESVS_2024__p1-1__c0003   ESVS_2024  CLINICAL PRACTICE GUIDELINE DOCUMENT           1         1     clinical          216        1119
3   ESVS_2024__p1-1__c0004   ESVS_2024  CLINICAL PRACTICE GUIDELINE DOCUMENT           1         1     clinical          209         979
4   ESVS_2024__p1-1__c0005   ESVS_2024  CLINICAL PRACTICE GUIDELINE DOCUMENT           1         1     clinical          220         966
5   ESVS_2024__p1-1__c0006   ESVS_2024  CLINICAL PRACTICE GUIDELINE DOCUMENT           1         1     clinical          217         861
6   ESVS_2024__p1-1__c0007   ESVS_2024  CLINICAL PRACTICE GUIDELINE DOCUMENT           1         1     clinical          205         698
7   ESVS_2024__p1-1__c0008   ESVS_2024  CLINICAL PRACTICE GUIDELINE DOCUMENT           1         1     clinical          199         642
8   ESVS_2024__p1-1__c0009   ESVS_2024  CLINICAL PRACTICE GUIDELINE DOCUMENT           1         1     clinical          220         728
9   ESVS_2024__p1-1__c0010   ESVS_2024  CLINICAL PRACTICE GUIDELINE DOCUMENT           1         1     clinical          215         719
10  ESVS_2024__p3-3__c0011   ESVS_2024  CLINICAL PRACTICE GUIDELINE DOCUMENT           3         3          toc          186         407
11  ESVS_2024__p3-3__c0012   ESVS_2024  CLINICAL PRACTICE GUIDELINE DOCUMENT           3         3          toc          191         414

Token distribution (tokenizer of the embedding model)

                                                  value
model_name       sentence-transformers/all-MiniLM-L6-v2
token_limit                                         256
n_chunks                                           2116
min_tokens                                           12
max_tokens                                          254
mean_tokens                                      194.78
median_tokens                                     206.0
exceeding_limit                                       0

Chunks by content type (low-value types are kept on disk but excluded from the index)

              n_chunks
content_type
clinical          1330
reference          661
toc                103
boilerplate         14
title_only           8

Sample chunks - metadata AND the real chunk text
----------------------------------------------------------------------------------------
chunk_id     : ESVS_2024__p1-1__c0001
document     : Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
is_guideline : True
page         : 1 (pages 1-1)
section      : CLINICAL PRACTICE GUIDELINE DOCUMENT [detected]
content_type : clinical
tokens       : 220   chars: 696
text         :
CLINICAL PRACTICE GUIDELINE DOCUMENT
Editor’s Choice – European Society for Vascular Surgery (ESVS) 2024 Clinical
Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery
Aneurysms5
Anders Wanhainen a,*, Isabelle Van Herzeele a, Frederico Bastos Goncalves a, Sergi Bellmunt Montoya a, Xavier Berard a, Jonathan R. Boyle a,
Mario D’Oria a, Carlota F. Prendes a, Christos D. Karkos a, Arkadiusz Kazimierczak a, Mark J.W. Koelemay a, Tilo Kölbel a, Kevin Mani a,
Germano Melissano a, Janet T. Powell a, Santi Trimarchi a, Nikolaos Tsilimparis a
ESVS Guidelines Committee b, George A. Antoniou, Martin Björck, Raphael Coscas, Nuno V. Dias, Philippe Kolh, Sandro Lepidi, Barend M.E. Mees,

----------------------------------------------------------------------------------------
chunk_id     : ESVS_2024__p1-1__c0002
document     : Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
is_guideline : True
page         : 1 (pages 1-1)
section      : CLINICAL PRACTICE GUIDELINE DOCUMENT [detected]
content_type : clinical
tokens       : 206   chars: 754
text         :
Antoniou, Martin Björck, Raphael Coscas, Nuno V. Dias, Philippe Kolh, Sandro Lepidi, Barend M.E. Mees,
Timothy A. Resch, Jean Baptiste Ricco, Riikka Tulamo, Christopher P. Twine
Document Reviewers c, Daniela Branzan, Stephen W.K. Cheng, Ronald L. Dalman, Florian Dick, Jonathan Golledge, Stephan Haulon,
Joost A. van Herwaarden, Nikola S. Ilic, Arkadiusz Jawien, Tara M. Mastracci, Gustavo S. Oderich, Fabio Verzini, Kak Khee Yeung
Objective: The European Society for Vascular Surgery (ESVS) has developed clinical practice guidelines for the care of patients with aneurysms of the abdominal aorta and iliac arteries in succession to the 2011 and 2019 versions, with the aim of assisting physicians a ...

----------------------------------------------------------------------------------------
chunk_id     : NICE_NG156__p1-1__c0001
document     : Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
is_guideline : True
page         : 1 (pages 1-1)
section      : Abdominal aortic aneurysm: diagnosis and management [detected]
content_type : boilerplate
tokens       : 76   chars: 248
text         :
Abdominal aortic aneurysm: diagnosis and management
NICE guideline
Published: 19 March 2020 www.nice.org.uk/guidance/ng156
© NICE 2025. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights).

----------------------------------------------------------------------------------------
chunk_id     : NICE_NG156__p2-2__c0002
document     : Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
is_guideline : True
page         : 2 (pages 2-2)
section      : Your responsibility [detected]
content_type : clinical
tokens       : 222   chars: 1290
text         :
Your responsibility
The recommendations in this guideline represent the view of NICE, arrived at after careful consideration of the evidence available. When exercising their judgement, professionals and practitioners are expected to take this guideline fully into account, alongside the individual needs, preferences and values of their patients or the people using their service.
It is not mandatory to apply the recommendations, and the guideline does not override the responsibility to make decisions appropriate to the circumstances of the individual, in consultation with them and their families and carers or guardian.
All problems (adverse events) related to a medicine or medical device used  ...

----------------------------------------------------------------------------------------
chunk_id     : SVS_2018__p1-1__c0001
document     : Care of Patients with an Abdominal Aortic Aneurysm (SVS_2018)
is_guideline : True
page         : 1 (pages 1-1)
section      : Care of Patients with an [detected]
content_type : title_only
tokens       : 31   chars: 134
text         :
Care of Patients with an
Abdominal Aortic Aneurysm
2018 Practice Guidelines from the
Society for Vascular Surgery vsweb.org/Guidelines

----------------------------------------------------------------------------------------
chunk_id     : SVS_2018__p2-2__c0002
document     : Care of Patients with an Abdominal Aortic Aneurysm (SVS_2018)
is_guideline : True
page         : 2 (pages 2-2)
section      : J Vasc Surg. 2018 Jan;67(1):2–77.e2 [detected]
content_type : clinical
tokens       : 110   chars: 492
text         :
J Vasc Surg. 2018 Jan;67(1):2–77.e2
About the guidelines
Published January 2018 in Journal of Vascular Surgery, updating previous guidelines published in 2009 (and 2003)
112 recommendations
+ 774 supporting references
14 international experts

Table:
About the guidelines Published January 2018 in Journal of Vascular Surgery, updating previous guidelines published in 2009 (and 2003) 14 international experts J VascSurg. 2018 Jan;67(1):2–77.e2 112 recommendations + 774 supporting references

----------------------------------------------------------------------------------------
chunk_id     : USPSTF_2019__p1-1__c0001
document     : Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
is_guideline : True
page         : 1 (pages 1-1)
section      : Screening for Abdominal Aortic Aneurysm [detected]
content_type : clinical
tokens       : 216   chars: 972
text         :
Screening for Abdominal Aortic Aneurysm
US Preventive Services Task Force Recommendation Statement
US Preventive Services Task Force
IMPORTANCE An abdominal aortic aneurysm (AAA) is typically defined as aortic enlargement with a diameter of 3.0 cm or larger. The prevalence of AAA has declined over the past 2 decades among screened men 65 years or older in various European countries. The current prevalence of AAA in the United States is unclear because of the low uptake of screening.
Most AAAs are asymptomatic until they rupture. Although the risk for rupture varies greatly by aneurysm size, the associated risk for death with rupture is as high as 81%.
OBJECTIVE To update its 2014 recommendat ...

----------------------------------------------------------------------------------------
chunk_id     : USPSTF_2019__p1-1__c0002
document     : Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
is_guideline : True
page         : 1 (pages 1-1)
section      : Screening for Abdominal Aortic Aneurysm [detected]
content_type : clinical
tokens       : 209   chars: 1017
text         :
OBJECTIVE To update its 2014 recommendation, the USPSTF commissioned a review of the evidence on the effectiveness of 1-time and repeated screening for AAA, the associated harms of screening, and the benefits and harms of available treatments for small AAAs
(3.0-5.4 cm in diameter) identified through screening.
POPULATION This recommendation applies to asymptomatic adults 50 years or older.
However, the randomized trial evidence focuses almost entirely on men aged 65 to 75 years.
EVIDENCE ASSESSMENT Based on a review of the evidence, the USPSTF concludes with moderate certainty that screening for AAA in men aged 65 to 75 years who have ever smoked is of moderate net benefit. The USPSTF concl ...


EXCEEDING_LIMIT = 0

## Local embeddings and vector index

Model: `sentence-transformers/all-MiniLM-L6-v2` (configurable in `clinical_rag.DEFAULT_MODEL`).
Index: cosine similarity over L2-normalized NumPy vectors, with chunk metadata stored beside the matrix.

In [4]:
embed_result = cr.run_embedding_index(PROJECT_ROOT, model_name=cr.DEFAULT_MODEL)
print("Embedded chunks:", embed_result["total_embedded"])
print("Model:", embed_result["model_name"])
print("Dimension:", embed_result["embedding_dim"])
print("Failed embeddings:", embed_result["failed"])
print("Index files:")
for key, path in embed_result["paths"].items():
    print(f" - {key}: {path}")

index_dir = PROJECT_ROOT / "data" / "embeddings"
meta = json.loads((index_dir / "index_meta.json").read_text(encoding="utf-8"))
assert meta["n_vectors"] == embed_result["total_embedded"]
assert (index_dir / "embeddings.npy").stat().st_size > 0
print("\nNotebook 02 embeddings validated.")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4430.86it/s]

Batches:   0%|          | 0/42 [00:00<?, ?it/s]

Batches:   2%|▏         | 1/42 [00:02<01:40,  2.45s/it]

Batches:   5%|▍         | 2/42 [00:04<01:18,  1.95s/it]

Batches:   7%|▋         | 3/42 [00:05<01:09,  1.78s/it]

Batches:  10%|▉         | 4/42 [00:07<01:07,  1.77s/it]

Batches:  12%|█▏        | 5/42 [00:08<01:02,  1.70s/it]

Batches:  14%|█▍        | 6/42 [00:10<00:59,  1.66s/it]

Batches:  17%|█▋        | 7/42 [00:12<00:57,  1.66s/it]

Batches:  19%|█▉        | 8/42 [00:13<00:55,  1.63s/it]

Batches:  21%|██▏       | 9/42 [00:15<00:54,  1.64s/it]

Batches:  24%|██▍       | 10/42 [00:16<00:51,  1.62s/it]

Batches:  26%|██▌       | 11/42 [00:18<00:49,  1.58s/it]

Batches:  29%|██▊       | 12/42 [00:19<00:46,  1.55s/it]

Batches:  31%|███       | 13/42 [00:21<00:44,  1.54s/it]

Batches:  33%|███▎      | 14/42 [00:23<00:43,  1.54s/it]

Batches:  36%|███▌      | 15/42 [00:24<00:42,  1.58s/it]

Batches:  38%|███▊      | 16/42 [00:26<00:42,  1.64s/it]

Batches:  40%|████      | 17/42 [00:28<00:40,  1.62s/it]

Batches:  43%|████▎     | 18/42 [00:29<00:38,  1.60s/it]

Batches:  45%|████▌     | 19/42 [00:31<00:36,  1.61s/it]

Batches:  48%|████▊     | 20/42 [00:32<00:34,  1.59s/it]

Batches:  50%|█████     | 21/42 [00:34<00:33,  1.58s/it]

Batches:  52%|█████▏    | 22/42 [00:35<00:31,  1.59s/it]

Batches:  55%|█████▍    | 23/42 [00:37<00:31,  1.64s/it]

Batches:  57%|█████▋    | 24/42 [00:39<00:30,  1.67s/it]

Batches:  60%|█████▉    | 25/42 [00:41<00:28,  1.69s/it]

Batches:  62%|██████▏   | 26/42 [00:42<00:27,  1.71s/it]

Batches:  64%|██████▍   | 27/42 [00:44<00:25,  1.67s/it]

Batches:  67%|██████▋   | 28/42 [00:46<00:23,  1.65s/it]

Batches:  69%|██████▉   | 29/42 [00:47<00:21,  1.62s/it]

Batches:  71%|███████▏  | 30/42 [00:49<00:19,  1.59s/it]

Batches:  74%|███████▍  | 31/42 [00:50<00:17,  1.57s/it]

Batches:  76%|███████▌  | 32/42 [00:52<00:15,  1.56s/it]

Batches:  79%|███████▊  | 33/42 [00:53<00:13,  1.54s/it]

Batches:  81%|████████  | 34/42 [00:55<00:12,  1.54s/it]

Batches:  83%|████████▎ | 35/42 [00:56<00:10,  1.54s/it]

Batches:  86%|████████▌ | 36/42 [00:58<00:09,  1.55s/it]

Batches:  88%|████████▊ | 37/42 [01:00<00:07,  1.57s/it]

Batches:  90%|█████████ | 38/42 [01:01<00:06,  1.56s/it]

Batches:  93%|█████████▎| 39/42 [01:03<00:04,  1.54s/it]

Batches:  95%|█████████▌| 40/42 [01:04<00:03,  1.64s/it]

Batches:  98%|█████████▊| 41/42 [01:06<00:01,  1.63s/it]

Batches: 100%|██████████| 42/42 [01:07<00:00,  1.30s/it]

Batches: 100%|██████████| 42/42 [01:07<00:00,  1.60s/it]

Embedded chunks: 1330
Model: sentence-transformers/all-MiniLM-L6-v2
Dimension: 384
Failed embeddings: []
Index files:
 - dir: data/embeddings
 - vectors: data/embeddings/embeddings.npy
 - meta: data/embeddings/index_meta.json
 - chunks: data/embeddings/embedded_chunks.json

Notebook 02 embeddings validated.