# 03 - AAA retrieval

Runs 10 clinical AAA queries against the local dense vector index and displays the
retrieved source chunks with their metadata (document, section, page, chunk ID,
similarity score, text).

This notebook retrieves and displays source text only. It does not generate answers.

In [1]:
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

try:
    from IPython.display import display
except ImportError:
    def display(obj):
        print(obj)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 90)
pd.set_option("display.width", 200)

cwd = Path.cwd().resolve()
for candidate in [cwd, cwd / "notebooks", cwd.parent]:
    if (candidate / "clinical_rag.py").exists():
        sys.path.insert(0, str(candidate))
        break
    if (candidate / "notebooks" / "clinical_rag.py").exists():
        sys.path.insert(0, str(candidate / "notebooks"))
        break

import clinical_chunking as cc
import clinical_preprocess as cp
import clinical_rag as cr

PROJECT_ROOT = cp.find_project_root()
index = cr.load_index(PROJECT_ROOT)
# Loaded through cc.load_embedder so the pinned revision applies here too.
model = cc.load_embedder(index["model_name"])

print("Index type:", index["meta"]["index_type"], "| metric:", index["meta"]["metric"])
print("Embedding model:", index["model_name"])
print("Indexed vectors:", index["meta"]["n_vectors"], "x", index["meta"]["embedding_dim"])
print("Clinical queries:", len(cr.CLINICAL_QUERIES))

C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2233.94it/s]

Index type: numpy_cosine | metric: cosine
Embedding model: sentence-transformers/all-MiniLM-L6-v2
Indexed vectors: 1330 x 384
Clinical queries: 10

## Indexed corpus

Only official guideline documents are indexed.

In [2]:
idx_df = pd.DataFrame(index["chunks"])
summary = (
    idx_df.groupby(["document_id", "document_name"])
    .agg(n_chunks=("chunk_id", "size"), pages=("page_number", "nunique"), max_tokens=("token_count", "max"))
    .reset_index()
)
display(summary)
print("total indexed chunks:", len(idx_df))

   document_id                                                                              document_name  n_chunks  pages  max_tokens
0    ESVS_2024  Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice...      1095    102         224
1   NICE_NG156                                        Abdominal aortic aneurysm: diagnosis and management       118     50         222
2     SVS_2018                                         Care of Patients with an Abdominal Aortic Aneurysm        44     37         254
3  USPSTF_2019  Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendat...        73      7         222

total indexed chunks: 1330

## Clinical queries and retrieved chunks

Top-5 chunks per query, each shown with document, section, page, chunk ID, similarity
score and the chunk text.

In [3]:
TOP_K = 5
query_runs = []

for q_i, query in enumerate(cr.CLINICAL_QUERIES, start=1):
    hits = cr.retrieve(query, index, model=model, top_k=TOP_K)
    query_runs.append({"query_id": q_i, "query": query, "hits": hits})
    print("=" * 90)
    print(f"Q{q_i}. {query}")
    print("=" * 90)
    for hit in hits:
        print(cr.format_hit(hit, preview_chars=500))
        print("-" * 90)

==========================================================================================
Q1. What are the recommendations for screening for abdominal aortic aneurysm?
==========================================================================================
rank 1  score=0.7281
chunk_id: ESVS_2024__p19-19__c0260
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: Recommendation 9
page: 19 (pages 19-19)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: recommendation_id=nan, grade=nan, evidence_level=nan
source excerpt: Recommendation 9
Changed
Computed tomography angiography is recommended for treatment planning once the anteroposterior diameter threshold for elective abdominal aortic aneurysm repair has been met on ultrasound, and for the diagnosis of rupture.
Class
Level
References
ToE
I
C
Long et al. (2012),112
Oliver-Williams et al (2019),117
Biancari et al. (2013)122
Recommendation 10
Changed
Aortic diamete
chunk text:
Recommendation 9
Changed
Computed tomography angiography is recommended for treatment planning once the anteroposterior diameter threshold for elective abdominal aortic aneurysm repair has been met on ultrasound, and for the diagnosis of rupture.
Class
Level
References
ToE
I
C
Long et al. (2012),112
Oliver-Williams et al (2019),117
Biancari et al. (2013)122
Recommendation 10
Changed
Aortic diameter measurement with computed tomography angiography is recommended using dedicated postprocessing sof ...

------------------------------------------------------------------------------------------
rank 2  score=0.7279
chunk_id: USPSTF_2019__p3-3__c0027
document: Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
section: Treatment
page: 3 (pages 3-3)
source_file: abdom-aortic-aneurysm-screening-final-rs.pdf
recommendation metadata: none in this chunk
source excerpt: Clinicians should understand the evidence but individualize decision-making to the specific patient or situation.
Asymptomatic adults
How often?
One-time screening
What are other relevant USPSTF recommendations?
The USPSTF has made recommendations on screening for carotid artery stenosis and screening for peripheral arterial disease.
These recommendations are available at https://www.uspreventives
chunk text:
Clinicians should understand the evidence but individualize decision-making to the specific patient or situation.
Asymptomatic adults
How often?
One-time screening
What are other relevant USPSTF recommendations?
The USPSTF has made recommendations on screening for carotid artery stenosis and screening for peripheral arterial disease.
These recommendations are available at https://www.uspreventiveservicestaskforce.org.
This recommendation is consistent with the 2014 USPSTF recommendation. Family  ...

------------------------------------------------------------------------------------------
rank 3  score=0.7239
chunk_id: NICE_NG156__p29-29__c0095
document: Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
section: Rationale and impact
page: 29 (pages 29-29)
source_file: abdominal-aortic-aneurysm-diagnosis-and-management-pdf-66141843642565.pdf
recommendation metadata: none in this chunk
source excerpt: Men can then self-refer if they feel screening is right for them. Evidence from cross-sectional studies also found that people of Hispanic, African-American and Asian family origin were individually less likely than people of European family origin to have an
AAA, so the committee wished to raise awareness of this.
Aortic ultrasound is recommended because it is the standard technique used in clini
chunk text:
Men can then self-refer if they feel screening is right for them. Evidence from cross-sectional studies also found that people of Hispanic, African-American and Asian family origin were individually less likely than people of European family origin to have an
AAA, so the committee wished to raise awareness of this.
Aortic ultrasound is recommended because it is the standard technique used in clinical practice and in the screening programme. It has high diagnostic accuracy, and is associated with ...

------------------------------------------------------------------------------------------
rank 4  score=0.7236
chunk_id: NICE_NG156__p9-9__c0045
document: Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
section: Imaging technique
page: 9 (pages 9-9)
source_file: abdominal-aortic-aneurysm-diagnosis-and-management-pdf-66141843642565.pdf
recommendation metadata: recommendation_id=1.1.10, grade=nan, evidence_level=nan
source excerpt: For a short explanation of why the committee made these recommendations and how they might affect practice, see the rationale and impact section on identifying symptomatic or ruptured abdominal aortic aneurysms.
Full details of the evidence and the committee's discussion are in evidence review B:
imaging techniques to diagnose abdominal aortic aneurysms and evidence review N:
signs, symptoms and r
chunk text:
For a short explanation of why the committee made these recommendations and how they might affect practice, see the rationale and impact section on identifying symptomatic or ruptured abdominal aortic aneurysms.
Full details of the evidence and the committee's discussion are in evidence review B:
imaging techniques to diagnose abdominal aortic aneurysms and evidence review N:
signs, symptoms and risk factors predicting ruptured or symptomatic unruptured aneurysms before arrival at the hospital,  ...

------------------------------------------------------------------------------------------
rank 5  score=0.7171
chunk_id: ESVS_2024__p95-95__c1178
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: INFORMATION FOR PATIENTS
page: 95 (pages 95-95)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: An abdominal aortic aneurysm is a swelling or ballooning of the main artery in the body as it takes blood through the belly to supply the legs (Fig. 14A). These aneurysms are very rare before the age of 60 years. They are more common in people who have smoked (current smokers or ex-smokers) than in those who have never smoked.They are also more common in men than in women. A minority of patients m
chunk text:
An abdominal aortic aneurysm is a swelling or ballooning of the main artery in the body as it takes blood through the belly to supply the legs (Fig. 14A). These aneurysms are very rare before the age of 60 years. They are more common in people who have smoked (current smokers or ex-smokers) than in those who have never smoked.They are also more common in men than in women. A minority of patients may have a strong genetic cause for the abdominal aortic aneurysm.
Most aneurysms do not cause any sy ...

------------------------------------------------------------------------------------------
==========================================================================================
Q2. What AAA diameter is generally associated with consideration of elective repair?
==========================================================================================
rank 1  score=0.7688
chunk_id: ESVS_2024__p26-26__c0351
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: ABDOMINAL AORTIC ANEURYSM
page: 26 (pages 26-26)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: On the contrary, based on the NAAASP data it has been suggested to raise the diameter threshold to 60 mm when based on
CTA.254 Although it is possible that the threshold should be raised in the future, the GWC does not believe there is suf- ﬁcient support at this time. Nevertheless, the GWC has chosen to issue a new strong negative recommendation of elective repair of AAA < 55 mm, and to downgrade
chunk text:
On the contrary, based on the NAAASP data it has been suggested to raise the diameter threshold to 60 mm when based on
CTA.254 Although it is possible that the threshold should be raised in the future, the GWC does not believe there is suf- ﬁcient support at this time. Nevertheless, the GWC has chosen to issue a new strong negative recommendation of elective repair of AAA < 55 mm, and to downgrade the recommendation on the threshold for considering repair in men (from Class I and LoE A to Class  ...

------------------------------------------------------------------------------------------
rank 2  score=0.7128
chunk_id: USPSTF_2019__p3-3__c0024
document: Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
section: Treatment
page: 3 (pages 3-3)
source_file: abdom-aortic-aneurysm-screening-final-rs.pdf
recommendation metadata: none in this chunk
source excerpt: (defined as an AAA <3 cm in diameter).1
Treatment
Treatment of AAA depends on aneurysm size, the risk of rupture, and the risk of operative mortality. Larger size is associated with an increased risk of rupture. The annual risk for rupture is nearly 0% for persons with AAAs between 3.0 and 3.9 cm in diameter, 1% for those with AAAs between 4.0 and 4.9 cm in diameter, and 11% for those with AAAs be
chunk text:
(defined as an AAA <3 cm in diameter).1
Treatment
Treatment of AAA depends on aneurysm size, the risk of rupture, and the risk of operative mortality. Larger size is associated with an increased risk of rupture. The annual risk for rupture is nearly 0% for persons with AAAs between 3.0 and 3.9 cm in diameter, 1% for those with AAAs between 4.0 and 4.9 cm in diameter, and 11% for those with AAAs between 5.0 and 5.9 cm in diameter.1 Surgical repair is standard practice for men with an AAA of 5.5 c ...

------------------------------------------------------------------------------------------
rank 3  score=0.6929
chunk_id: ESVS_2024__p26-26__c0350
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: ABDOMINAL AORTIC ANEURYSM
page: 26 (pages 26-26)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: Women with AAA size 61 e 70 m had a three year cumulative incidence of rupture of 12.8% compared with 4.5% in men (p ¼ .002).76
In conclusion, in men the risk of rupture is very low (0.3 e
0.8% per year) for AAAs with a diameter below 55 mm measured with US, which translates to a diameter on CTA between 55 e 62 mm depending on which measurement methodology is used.Therefore,there is no need to low
chunk text:
Women with AAA size 61 e 70 m had a three year cumulative incidence of rupture of 12.8% compared with 4.5% in men (p ¼ .002).76
In conclusion, in men the risk of rupture is very low (0.3 e
0.8% per year) for AAAs with a diameter below 55 mm measured with US, which translates to a diameter on CTA between 55 e 62 mm depending on which measurement methodology is used.Therefore,there is no need to lower the diameter threshold for repair or to perform a CTA when US measures the AAA diameter < 55 mm i ...

------------------------------------------------------------------------------------------
rank 4  score=0.6857
chunk_id: ESVS_2024__p26-26__c0349
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: ABDOMINAL AORTIC ANEURYSM
page: 26 (pages 26-26)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: This is further underlined by a VASCUNET study, showing that the average diameter at repair varies between countries, but this does not translate to a reduced number of operations for rAAA.253
A recent prospective surveillance registry study, including
332 patients with large AAAs undergoing delayed repair for more than one year and 1 033 patients with large AAAs not undergoing repair, most often
chunk text:
This is further underlined by a VASCUNET study, showing that the average diameter at repair varies between countries, but this does not translate to a reduced number of operations for rAAA.253
A recent prospective surveillance registry study, including
332 patients with large AAAs undergoing delayed repair for more than one year and 1 033 patients with large AAAs not undergoing repair, most often due to patient preference or comorbidity, reported a three year cumulative incidence of rupture of 3 ...

------------------------------------------------------------------------------------------
rank 5  score=0.6549
chunk_id: USPSTF_2019__p3-3__c0025
document: Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
section: Treatment
page: 3 (pages 3-3)
source_file: abdom-aortic-aneurysm-screening-final-rs.pdf
recommendation metadata: none in this chunk
source excerpt: The annual risk for rupture is nearly 0% for persons with AAAs between 3.0 and 3.9 cm in diameter, 1% for those with AAAs between 4.0 and 4.9 cm in diameter, and 11% for those with AAAs between 5.0 and 5.9 cm in diameter.1 Surgical repair is standard practice for men with an AAA of 5.5 cm or larger in diameter or an AAA larger than 4.0 cm in diameter that has rapidly increased in size (defined as
chunk text:
The annual risk for rupture is nearly 0% for persons with AAAs between 3.0 and 3.9 cm in diameter, 1% for those with AAAs between 4.0 and 4.9 cm in diameter, and 11% for those with AAAs between 5.0 and 5.9 cm in diameter.1 Surgical repair is standard practice for men with an AAA of 5.5 cm or larger in diameter or an AAA larger than 4.0 cm in diameter that has rapidly increased in size (defined as an increase of 1.0 cm in diameter over a 1-year period). Endovascular aneurysm repair (EVAR) has bec ...

------------------------------------------------------------------------------------------
==========================================================================================
Q3. What surveillance strategy is recommended for small abdominal aortic aneurysms?
==========================================================================================
rank 1  score=0.7383
chunk_id: ESVS_2024__p22-22__c0297
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: ABDOMINAL AORTIC ANEURYSM
page: 22 (pages 22-22)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: Sogaard et al. (2012),179
Rockley et al. (2020)180
Recommendation 14
Changed
Women should be considered for imaging surveillance using ultrasound every ﬁve years for a sub-aneurysmal aorta 25 e
29 mm in diameter, every three years for abdominal aortic aneurysms 30 e 39 mm in diameter, annually for aneurysms
40 e 44 mm, and every six months for aneurysms ‡ 45 mm, taking into account life expectancy
chunk text:
Sogaard et al. (2012),179
Rockley et al. (2020)180
Recommendation 14
Changed
Women should be considered for imaging surveillance using ultrasound every ﬁve years for a sub-aneurysmal aorta 25 e
29 mm in diameter, every three years for abdominal aortic aneurysms 30 e 39 mm in diameter, annually for aneurysms
40 e 44 mm, and every six months for aneurysms ‡ 45 mm, taking into account life expectancy, suitability for future repair, and patient preferences.
Class
Level
References
ToE
IIa
C
Bown et a ...

------------------------------------------------------------------------------------------
rank 2  score=0.7190
chunk_id: NICE_NG156__p29-29__c0096
document: Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
section: Rationale and impact
page: 29 (pages 29-29)
source_file: abdominal-aortic-aneurysm-diagnosis-and-management-pdf-66141843642565.pdf
recommendation metadata: none in this chunk
source excerpt: The committee recommended that people with aneurysms less than 5.5 cm in diameter are seen within 12 weeks of diagnosis because this is the timeframe set by the NHS AAA screening programme.
How the recommendations might affect practice
The recommendations outlining key risk factors will increase the number of people being
Abdominal aortic aneurysm: diagnosis and management (NG156)
© NICE 2025. All
chunk text:
The committee recommended that people with aneurysms less than 5.5 cm in diameter are seen within 12 weeks of diagnosis because this is the timeframe set by the NHS AAA screening programme.
How the recommendations might affect practice
The recommendations outlining key risk factors will increase the number of people being
Abdominal aortic aneurysm: diagnosis and management (NG156)
© NICE 2025. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of ...

------------------------------------------------------------------------------------------
rank 3  score=0.7061
chunk_id: ESVS_2024__p6-6__c0097
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: Open Surgical Repair
page: 6 (pages 6-6)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: 158. For patients with abdominal aortic aneurysms with an underlying genetic cause, the threshold diameter for considering repair should be individualised, depending on the underlying genetics and anatomy.
159. Shared decision making should be facilitated during conversations around abdominal aortic aneurysm screening, surveillance and the management of large asymptomatic abdominal aortic aneurysm
chunk text:
158. For patients with abdominal aortic aneurysms with an underlying genetic cause, the threshold diameter for considering repair should be individualised, depending on the underlying genetics and anatomy.
159. Shared decision making should be facilitated during conversations around abdominal aortic aneurysm screening, surveillance and the management of large asymptomatic abdominal aortic aneurysms being considered for repair
New Class IIa recommendations
15.
Patients with small abdominal aortic ...

------------------------------------------------------------------------------------------
rank 4  score=0.6908
chunk_id: NICE_NG156__p5-5__c0038
document: Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
section: Your responsibility
page: 5 (pages 5-5)
source_file: abdominal-aortic-aneurysm-diagnosis-and-management-pdf-66141843642565.pdf
recommendation metadata: none in this chunk
source excerpt: This guideline replaces TA167.
Overview
This guideline covers diagnosing and managing abdominal aortic aneurysms. It aims to improve care by helping people who are at risk to get tested, specifying how often to monitor asymptomatic aneurysms, and identifying when aneurysm repair is needed and which procedure will work best.
The recommendations in this guideline were developed before the COVID-19 p
chunk text:
This guideline replaces TA167.
Overview
This guideline covers diagnosing and managing abdominal aortic aneurysms. It aims to improve care by helping people who are at risk to get tested, specifying how often to monitor asymptomatic aneurysms, and identifying when aneurysm repair is needed and which procedure will work best.
The recommendations in this guideline were developed before the COVID-19 pandemic.
Who is it for?
• Healthcare professionals

==========================================================================================

Q4. What are the indications for endovascular aneurysm repair?
==========================================================================================
rank 1  score=0.7132
chunk_id: ESVS_2024__p83-83__c1036
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: None
page: 83 (pages 83-83)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: The aim of surgical treatment of IAAs is to exclude the aneurysm from the circulation to prevent further growth and rupture. Before the advent of endovascular repair in the early
1990s OSR was the mainstay of treatment of IAA. The steady shift towards endovascular techniques since 2000 has been associated with a signiﬁcant decrease in operative morbidity and mortality,1086 and a recent meta-analys
chunk text:
The aim of surgical treatment of IAAs is to exclude the aneurysm from the circulation to prevent further growth and rupture. Before the advent of endovascular repair in the early
1990s OSR was the mainstay of treatment of IAA. The steady shift towards endovascular techniques since 2000 has been associated with a signiﬁcant decrease in operative morbidity and mortality,1086 and a recent meta-analysis reported a perioperative mortality rate of 0.7% for endovascular repair.826
Furthermore, endovasc ...

------------------------------------------------------------------------------------------
rank 2  score=0.7069
chunk_id: ESVS_2024__p70-70__c0895
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: 30 Days post-operative CTA
page: 70 (pages 70-70)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: An alternative (possibly complimentary) strategy consists of evaluating the early (up to two years) evolution of the aneurysm sac. If shrinkage (> 5 mm) is observed, routine imaging can be waived as this is a proxy of successful
Unfavourable sac dynamic ?
Favourable sac dynamic § ?
Problem resolved ?
Individualised planning
Standard EVAR
CTA 5 years
30 Days post-operative CTA
Evaluate for re-inter
chunk text:
An alternative (possibly complimentary) strategy consists of evaluating the early (up to two years) evolution of the aneurysm sac. If shrinkage (> 5 mm) is observed, routine imaging can be waived as this is a proxy of successful
Unfavourable sac dynamic ?
Favourable sac dynamic § ?
Problem resolved ?
Individualised planning
Standard EVAR
CTA 5 years
30 Days post-operative CTA
Evaluate for re-intervention
Type 1 or 3 endoleak ?
Compromised seal * ?
CTA or DUS annually
Remaining problem ?
High ris ...

------------------------------------------------------------------------------------------
rank 3  score=0.7052
chunk_id: ESVS_2024__p72-72__c0920
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: ANEURYSMS
page: 72 (pages 72-72)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: Suggested diagnostic step up for occult undetermined
endoleaks after endovascular abdominal aortic aneurysm repair.
CTA¼computedtomographyangiography;DUS¼duplexultra-
sound; CEUS ¼ contrast enhanced ultrasound; MRI ¼ magnetic
resonanceimaging;18F-FDG/PET-CT¼positronemissiontomog-
raphy with 2-deoxy-2-fluorine-18-fluoro-D-glucose; WBCS ¼
whitebloodcellscintigraphy;OSR¼opensurgicalrepair.
chunk text:
Suggested diagnostic step up for occult undetermined
endoleaks after endovascular abdominal aortic aneurysm repair.
CTA¼computedtomographyangiography;DUS¼duplexultra-
sound; CEUS ¼ contrast enhanced ultrasound; MRI ¼ magnetic
resonanceimaging;18F-FDG/PET-CT¼positronemissiontomog-
raphy with 2-deoxy-2-fluorine-18-fluoro-D-glucose; WBCS ¼
whitebloodcellscintigraphy;OSR¼opensurgicalrepair.

------------------------------------------------------------------------------------------
rank 4  score=0.6938
chunk_id: NICE_NG156__p19-19__c0072
document: Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
section: 1.6 Repairing ruptured aneurysms
page: 19 (pages 19-19)
source_file: abdominal-aortic-aneurysm-diagnosis-and-management-pdf-66141843642565.pdf
recommendation metadata: recommendation_id=1.6.1, grade=nan, evidence_level=nan
source excerpt: Consider endovascular aneurysm repair (EVAR) or open surgical repair for people
Abdominal aortic aneurysm: diagnosis and management (NG156)
© NICE 2025. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights).
Page 19 of
chunk text:
Consider endovascular aneurysm repair (EVAR) or open surgical repair for people
Abdominal aortic aneurysm: diagnosis and management (NG156)
© NICE 2025. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights).
Page 19 of

------------------------------------------------------------------------------------------
rank 5  score=0.6898
chunk_id: ESVS_2024__p9-9__c0154
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: Table 1-continued
page: 9 (pages 9-9)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: Forpatientswithrupturedabdominalaorticaneurysm,apolicyofpermissivehypotensionisrecommended*(downgradedtoLoEC) 80. For patients with a ruptured abdominal aortic aneurysm and suitable anatomy, endovascular repair is recommended as the first treatmentoption(upgradedtoLoEA) 87. Patients operated on for an abdominal aortic aneurysm with new onset or worsening of lower limb ischaemia are recommended imm
chunk text:
Forpatientswithrupturedabdominalaorticaneurysm,apolicyofpermissivehypotensionisrecommended*(downgradedtoLoEC) 80. For patients with a ruptured abdominal aortic aneurysm and suitable anatomy, endovascular repair is recommended as the first treatmentoption(upgradedtoLoEA) 87. Patients operated on for an abdominal aortic aneurysm with new onset or worsening of lower limb ischaemia are recommended immediateevaluationofgraftrelatedproblems,suchaslimbkinkingorocclusion(upgradedtoLoEB) 130. Afterendova ...

------------------------------------------------------------------------------------------
==========================================================================================
Q5. What are the risk factors associated with abdominal aortic aneurysm?
==========================================================================================
rank 1  score=0.6718
chunk_id: ESVS_2024__p95-95__c1178
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: INFORMATION FOR PATIENTS
page: 95 (pages 95-95)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: An abdominal aortic aneurysm is a swelling or ballooning of the main artery in the body as it takes blood through the belly to supply the legs (Fig. 14A). These aneurysms are very rare before the age of 60 years. They are more common in people who have smoked (current smokers or ex-smokers) than in those who have never smoked.They are also more common in men than in women. A minority of patients m
chunk text:
An abdominal aortic aneurysm is a swelling or ballooning of the main artery in the body as it takes blood through the belly to supply the legs (Fig. 14A). These aneurysms are very rare before the age of 60 years. They are more common in people who have smoked (current smokers or ex-smokers) than in those who have never smoked.They are also more common in men than in women. A minority of patients may have a strong genetic cause for the abdominal aortic aneurysm.
Most aneurysms do not cause any sy ...

------------------------------------------------------------------------------------------
rank 2  score=0.6710
chunk_id: NICE_NG156__p29-29__c0096
document: Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
section: Rationale and impact
page: 29 (pages 29-29)
source_file: abdominal-aortic-aneurysm-diagnosis-and-management-pdf-66141843642565.pdf
recommendation metadata: none in this chunk
source excerpt: The committee recommended that people with aneurysms less than 5.5 cm in diameter are seen within 12 weeks of diagnosis because this is the timeframe set by the NHS AAA screening programme.
How the recommendations might affect practice
The recommendations outlining key risk factors will increase the number of people being
Abdominal aortic aneurysm: diagnosis and management (NG156)
© NICE 2025. All
chunk text:
The committee recommended that people with aneurysms less than 5.5 cm in diameter are seen within 12 weeks of diagnosis because this is the timeframe set by the NHS AAA screening programme.
How the recommendations might affect practice
The recommendations outlining key risk factors will increase the number of people being
Abdominal aortic aneurysm: diagnosis and management (NG156)
© NICE 2025. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of ...

------------------------------------------------------------------------------------------
rank 3  score=0.6566
chunk_id: NICE_NG156__p36-36__c0114
document: Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
section: Monitoring the risk of rupture
page: 36 (pages 36-36)
source_file: abdominal-aortic-aneurysm-diagnosis-and-management-pdf-66141843642565.pdf
recommendation metadata: none in this chunk
source excerpt: The evidence highlighted that none of the risk assessment tools had a high enough predictive accuracy at predicting postoperative outcomes. The specific tools listed are the ones for which evidence was available. This evidence led the committee to conclude that
Abdominal aortic aneurysm: diagnosis and management (NG156)
© NICE 2025. All rights reserved. Subject to Notice of rights (https://www.nic
chunk text:
The evidence highlighted that none of the risk assessment tools had a high enough predictive accuracy at predicting postoperative outcomes. The specific tools listed are the ones for which evidence was available. This evidence led the committee to conclude that
Abdominal aortic aneurysm: diagnosis and management (NG156)
© NICE 2025. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights).
Page 36 of

------------------------------------------------------------------------------------------
rank 4  score=0.6441
chunk_id: ESVS_2024__p98-98__c1201
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: Open surgical repair
page: 98 (pages 98-98)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: Given these risks some patients choose not to have a ruptured aneurysm repaired despite the fact that almost all patients with a ruptured aneurysm will die from this within a few days, without an emergency repair.
Ruptured aneurysms can be treated using the same operations as for planned surgery.
 Based on recent evidence we recommend that patients with a ruptured aneurysm who are suitable for an
chunk text:
Given these risks some patients choose not to have a ruptured aneurysm repaired despite the fact that almost all patients with a ruptured aneurysm will die from this within a few days, without an emergency repair.
Ruptured aneurysms can be treated using the same operations as for planned surgery.
 Based on recent evidence we recommend that patients with a ruptured aneurysm who are suitable for an endovascular repair should have this as the ﬁrst option wherever possible.
Rare causes of abdominal ...

------------------------------------------------------------------------------------------
rank 5  score=0.6359
chunk_id: NICE_NG156__p8-8__c0043
document: Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
section: Recommendations
page: 8 (pages 8-8)
source_file: abdominal-aortic-aneurysm-diagnosis-and-management-pdf-66141843642565.pdf
recommendation metadata: recommendation_id=1.1.7, grade=nan, evidence_level=nan
source excerpt: For a short explanation of why the committee made these recommendations and how they might affect practice, see the rationale and impact section on identifying asymptomatic abdominal aortic aneurysms.
Full details of the evidence and the committee's discussion are in evidence review A:
risk factors for predicting presence of an abdominal aortic aneurysm and evidence review B: imaging techniques to
chunk text:
For a short explanation of why the committee made these recommendations and how they might affect practice, see the rationale and impact section on identifying asymptomatic abdominal aortic aneurysms.
Full details of the evidence and the committee's discussion are in evidence review A:
risk factors for predicting presence of an abdominal aortic aneurysm and evidence review B: imaging techniques to diagnose abdominal aortic aneurysms.
Identifying symptomatic or ruptured abdominal aortic aneurysms ...

------------------------------------------------------------------------------------------
==========================================================================================
Q6. What imaging modality is recommended for diagnosis or surveillance of AAA?
==========================================================================================
rank 1  score=0.6702
chunk_id: ESVS_2024__p21-21__c0282
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: ABDOMINAL AORTIC ANEURYSM
page: 21 (pages 21-21)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: Guirguis-Blake et al. (2014)159
* What can be considered a high risk group varies based on local conditions, such as disease prevalence, life expectancy, and healthcare structure, see Table 6.
3.4. Incidental detection
Diagnostic imaging used for the investigation of other pathologies including back or chest pain, abdominal and genitourinary symptoms may also detect an AAA. While US and CT scan ar
chunk text:
Guirguis-Blake et al. (2014)159
* What can be considered a high risk group varies based on local conditions, such as disease prevalence, life expectancy, and healthcare structure, see Table 6.
3.4. Incidental detection
Diagnostic imaging used for the investigation of other pathologies including back or chest pain, abdominal and genitourinary symptoms may also detect an AAA. While US and CT scan are most commonly used, there are other imaging modalities including magnetic resonance imaging
(MRI), ...

------------------------------------------------------------------------------------------
rank 2  score=0.6675
chunk_id: USPSTF_2019__p3-3__c0022
document: Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
section: Treatment
page: 3 (pages 3-3)
source_file: abdom-aortic-aneurysm-screening-final-rs.pdf
recommendation metadata: none in this chunk
source excerpt: The primary method of screening for AAA is conventional abdominalduplexultrasonography.26Screeningwithultrasonographyisnoninvasive,issimpletoperform,hashighsensitivity(94%-100%)and specificity (98%-100%) for detecting AAA,1,27-31 and does not exposepatientstoradiation.Computedtomographyisanaccuratetool for identifying AAA; however, it is not recommended as a screening method because of the potenti
chunk text:
The primary method of screening for AAA is conventional abdominalduplexultrasonography.26Screeningwithultrasonographyisnoninvasive,issimpletoperform,hashighsensitivity(94%-100%)and specificity (98%-100%) for detecting AAA,1,27-31 and does not exposepatientstoradiation.Computedtomographyisanaccuratetool for identifying AAA; however, it is not recommended as a screening method because of the potential for harms from radiation exposure.1 Physical examination has been used in practice but has low se ...

------------------------------------------------------------------------------------------
rank 3  score=0.6431
chunk_id: ESVS_2024__p21-21__c0286
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: ABDOMINAL AORTIC ANEURYSM
page: 21 (pages 21-21)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: AAAs measuring 30 e 39 mm, yearly for 40 e 49 mm, and every six months for 50 e 54 mm.106 This has gained wide acceptance and was adopted by the ESVS 2019 AAA guidelines.2 At that time, a sex neutral surveillance regimen was given, not taking into account that women had a fourfold greater rupture risk, justifying more frequent surveillance.106
The safety of the RESCAN surveillance routine has also
chunk text:
AAAs measuring 30 e 39 mm, yearly for 40 e 49 mm, and every six months for 50 e 54 mm.106 This has gained wide acceptance and was adopted by the ESVS 2019 AAA guidelines.2 At that time, a sex neutral surveillance regimen was given, not taking into account that women had a fourfold greater rupture risk, justifying more frequent surveillance.106
The safety of the RESCAN surveillance routine has also been demonstrated in the national UK screening program, where the AAA risk of rupture was as low as ...

------------------------------------------------------------------------------------------
rank 4  score=0.6373
chunk_id: ESVS_2024__p26-26__c0344
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: ABDOMINAL AORTIC ANEURYSM
page: 26 (pages 26-26)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: AAAs < 55 mm, as opposed to the UK, where the small AAA repair rate was less than 10%.245 This paper has, however, been questioned for reasons relating to incidental detection rates, differences in coding systems, population structure, and total healthcare expenditure, as well as the indications for surgery and impact of population screening.246e248
Another topic of debate is which imaging modalit
chunk text:
AAAs < 55 mm, as opposed to the UK, where the small AAA repair rate was less than 10%.245 This paper has, however, been questioned for reasons relating to incidental detection rates, differences in coding systems, population structure, and total healthcare expenditure, as well as the indications for surgery and impact of population screening.246e248
Another topic of debate is which imaging modality and methodology should be used for decisions about repair. It is known that CTA measurements provi ...

------------------------------------------------------------------------------------------
rank 5  score=0.5994
chunk_id: USPSTF_2019__p3-3__c0029
document: Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
section: Treatment
page: 3 (pages 3-3)
source_file: abdom-aortic-aneurysm-screening-final-rs.pdf
recommendation metadata: none in this chunk

==========================================================================================
Q8. What are the recommendations for smoking cessation in patients with AAA?
==========================================================================================
rank 1  score=0.7535
chunk_id: NICE_NG156__p11-11__c0051
document: Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
section: Reducing the risk of rupture
page: 11 (pages 11-11)
source_file: abdominal-aortic-aneurysm-diagnosis-and-management-pdf-66141843642565.pdf
recommendation metadata: recommendation_id=1.2.1, grade=nan, evidence_level=nan
source excerpt: For a short explanation of why the committee made these recommendations and how they might affect practice, see the rationale and impact section on providing information to people with a diagnosed AAA.
Full details of the evidence and the committee's discussion are in evidence review K:
effectiveness of endovascular aneurysm repair, open surgical repair and non-surgical management of unruptured ab
chunk text:
For a short explanation of why the committee made these recommendations and how they might affect practice, see the rationale and impact section on providing information to people with a diagnosed AAA.
Full details of the evidence and the committee's discussion are in evidence review K:
effectiveness of endovascular aneurysm repair, open surgical repair and non-surgical management of unruptured abdominal aortic aneurysms.
1.2 Monitoring and reducing the risk of rupture
Reducing the risk of ruptu ...

------------------------------------------------------------------------------------------
rank 2  score=0.7337
chunk_id: USPSTF_2019__p2-2__c0017
document: Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
section: Summary of Recommendations
page: 2 (pages 2-2)
source_file: abdom-aortic-aneurysm-screening-final-rs.pdf
recommendation metadata: none in this chunk
source excerpt: Other risk factors include a history of other vascular aneurysms, coronary artery disease, cerebrovascular disease, atherosclerosis, hypercholesterolemia, and hypertension.17-19 Factors associated with a reduced risk include African American race, Hispanic ethnicity, Asian ethnicity, and diabetes.13,20-24 Risk factors for AAA rupture include older age, female sex, smoking, and elevated blood press
chunk text:
Other risk factors include a history of other vascular aneurysms, coronary artery disease, cerebrovascular disease, atherosclerosis, hypercholesterolemia, and hypertension.17-19 Factors associated with a reduced risk include African American race, Hispanic ethnicity, Asian ethnicity, and diabetes.13,20-24 Risk factors for AAA rupture include older age, female sex, smoking, and elevated blood pressure.1 Clinicians should consider the presence of comorbid conditions and not offering screening if p ...

------------------------------------------------------------------------------------------
rank 3  score=0.7182
chunk_id: SVS_2018__p20-20__c0020
document: Care of Patients with an Abdominal Aortic Aneurysm (SVS_2018)
section: Medical management during the period of
page: 20 (pages 20-20)
source_file: SVS_Guideline_AAA_Slides_0.pdf
recommendation metadata: recommendation_id=nan, grade=nan, evidence_level=B
source excerpt: Medical management during the period of
AAA surveillance
Recommendation
Level of recommendation
Quality of evidence
We recommend smoking cessation to reduce the risk of AAA growth and rupture.
1
B
We suggest not administering statins, doxycycline, roxithromycin,
ACE inhibitors, or angiotensin receptor blockers for the sole purpose of reducing the risk of AAA expansion and rupture.
2
C
We suggest n
chunk text:
Medical management during the period of
AAA surveillance
Recommendation
Level of recommendation
Quality of evidence
We recommend smoking cessation to reduce the risk of AAA growth and rupture.
1
B
We suggest not administering statins, doxycycline, roxithromycin,
ACE inhibitors, or angiotensin receptor blockers for the sole purpose of reducing the risk of AAA expansion and rupture.
2
C
We suggest not administering beta blocker therapy for the sole purpose of reducing the risk of AAA expansion and ...

------------------------------------------------------------------------------------------
rank 4  score=0.7069
chunk_id: USPSTF_2019__p2-2__c0012
document: Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
section: Summary of Recommendations
page: 2 (pages 2-2)
source_file: abdom-aortic-aneurysm-screening-final-rs.pdf
recommendation metadata: none in this chunk
source excerpt: Summary of Recommendations
Importance
An AAA is typically defined as aortic enlargement with a diameter of3.0cmorlarger.TheprevalenceofAAAhasdeclinedoverthepast
2 decades among screened men 65 years or older in various countries such as the United Kingdom, New Zealand, Sweden, and
Denmark.1-10 Population-based studies in men older than 60 years have found an AAA prevalence ranging from 1.2% to 3.3
chunk text:
Summary of Recommendations
Importance
An AAA is typically defined as aortic enlargement with a diameter of3.0cmorlarger.TheprevalenceofAAAhasdeclinedoverthepast
2 decades among screened men 65 years or older in various countries such as the United Kingdom, New Zealand, Sweden, and
Denmark.1-10 Population-based studies in men older than 60 years have found an AAA prevalence ranging from 1.2% to 3.3%.1-10 The reduction in prevalence is attributed to the decrease in smoking prevalenceovertime.Previ ...

------------------------------------------------------------------------------------------
rank 5  score=0.6892
chunk_id: USPSTF_2019__p3-3__c0029
document: Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
section: Treatment
page: 3 (pages 3-3)
source_file: abdom-aortic-aneurysm-screening-final-rs.pdf
recommendation metadata: none in this chunk
source excerpt: Evidence is insufficient to assess the balance of benefits and harms of screening for AAA with ultrasonography in women aged 65 to 75 years who have ever smoked or have a family history of AAA.
Assess risk. Risk factors for AAA include older age, male sex, smoking, and having a first-degree relative with an AAA.
The recommendation varies based on a patient’s sex, age, and smoking history. “Ever sm
chunk text:
Evidence is insufficient to assess the balance of benefits and harms of screening for AAA with ultrasonography in women aged 65 to 75 years who have ever smoked or have a family history of AAA.
Assess risk. Risk factors for AAA include older age, male sex, smoking, and having a first-degree relative with an AAA.
The recommendation varies based on a patient’s sex, age, and smoking history. “Ever smoker” is commonly defined as smoking 100 or more cigarettes.
1.
Screen. Abdominal duplex ultrasonogr ...

------------------------------------------------------------------------------------------
==========================================================================================
Q9. What are the recommendations for women regarding AAA screening?
==========================================================================================
rank 1  score=0.7064
chunk_id: USPSTF_2019__p3-3__c0029
document: Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
section: Treatment
page: 3 (pages 3-3)
source_file: abdom-aortic-aneurysm-screening-final-rs.pdf
recommendation metadata: none in this chunk
source excerpt: Evidence is insufficient to assess the balance of benefits and harms of screening for AAA with ultrasonography in women aged 65 to 75 years who have ever smoked or have a family history of AAA.
Assess risk. Risk factors for AAA include older age, male sex, smoking, and having a first-degree relative with an AAA.
The recommendation varies based on a patient’s sex, age, and smoking history. “Ever sm
chunk text:
Evidence is insufficient to assess the balance of benefits and harms of screening for AAA with ultrasonography in women aged 65 to 75 years who have ever smoked or have a family history of AAA.
Assess risk. Risk factors for AAA include older age, male sex, smoking, and having a first-degree relative with an AAA.
The recommendation varies based on a patient’s sex, age, and smoking history. “Ever smoker” is commonly defined as smoking 100 or more cigarettes.
1.
Screen. Abdominal duplex ultrasonogr ...

------------------------------------------------------------------------------------------
rank 2  score=0.6879
chunk_id: USPSTF_2019__p1-1__c0003
document: Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
section: Screening for Abdominal Aortic Aneurysm
page: 1 (pages 1-1)
source_file: abdom-aortic-aneurysm-screening-final-rs.pdf
recommendation metadata: recommendation_id=nan, grade=nan, evidence_level=nan
source excerpt: AAA in men aged 65 to 75 years who have never smoked is of small net benefit. The USPSTF concludes that the evidence is insufficient to determine the net benefit of screening for AAA in women aged 65 to 75 years who have ever smoked or have a family history of AAA. The
USPSTF concludes with moderate certainty that the harms of screening for AAA in women aged 65 to 75 years who have never smoked an
chunk text:
AAA in men aged 65 to 75 years who have never smoked is of small net benefit. The USPSTF concludes that the evidence is insufficient to determine the net benefit of screening for AAA in women aged 65 to 75 years who have ever smoked or have a family history of AAA. The
USPSTF concludes with moderate certainty that the harms of screening for AAA in women aged 65 to 75 years who have never smoked and have no family history of AAA outweigh the benefits.
RECOMMENDATIONS The USPSTF recommends 1-time  ...

------------------------------------------------------------------------------------------
rank 3  score=0.6760
chunk_id: USPSTF_2019__p2-2__c0016
document: Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
section: Summary of Recommendations
page: 2 (pages 2-2)
source_file: abdom-aortic-aneurysm-screening-final-rs.pdf
recommendation metadata: none in this chunk
source excerpt: In this Recommendation Statement, the recommendations are stratified by “men” and “women,” although the net benefit estimates are driven by biologic sex (ie, male/female) rather than gender identity. Persons should consider their sex at birth to determine which recommendation best applies to them.
Assessment of Risk
Important risk factors for AAA include older age, male sex, smoking, and having a
chunk text:
In this Recommendation Statement, the recommendations are stratified by “men” and “women,” although the net benefit estimates are driven by biologic sex (ie, male/female) rather than gender identity. Persons should consider their sex at birth to determine which recommendation best applies to them.
Assessment of Risk
Important risk factors for AAA include older age, male sex, smoking, and having a first-degree relative with an AAA.13-16
Other risk factors include a history of other vascular aneur ...

------------------------------------------------------------------------------------------
rank 4  score=0.6724
chunk_id: USPSTF_2019__p6-6__c0068
document: Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
section: Treatment
page: 6 (pages 6-6)
source_file: abdom-aortic-aneurysm-screening-final-rs.pdf
recommendation metadata: none in this chunk
source excerpt: The USPSTF did not expand the scope of its recommendation beyond the populations justified by its review of the current evidence andrecommendsresearchaboutthebenefitsandharmsofscreening in these groups.
Research Needs and Gaps
Addressingseveralkeyresearchgapscouldhelpinformthebenefit of screening for AAA in US-based populations1:
• Although evidence shows that women who smoke or have a family hist
chunk text:
The USPSTF did not expand the scope of its recommendation beyond the populations justified by its review of the current evidence andrecommendsresearchaboutthebenefitsandharmsofscreening in these groups.
Research Needs and Gaps
Addressingseveralkeyresearchgapscouldhelpinformthebenefit of screening for AAA in US-based populations1:
• Although evidence shows that women who smoke or have a family history are at increased risk for AAA compared with nonsmoking women without a family history, evidence  ...

------------------------------------------------------------------------------------------
rank 5  score=0.6692
chunk_id: USPSTF_2019__p1-1__c0002
document: Screening for Abdominal Aortic Aneurysm: US Preventive Services Task Force Recommendation Statement (USPSTF_2019)
section: Screening for Abdominal Aortic Aneurysm
page: 1 (pages 1-1)
source_file: abdom-aortic-aneurysm-screening-final-rs.pdf
recommendation metadata: none in this chunk
source excerpt: OBJECTIVE To update its 2014 recommendation, the USPSTF commissioned a review of the evidence on the effectiveness of 1-time and repeated screening for AAA, the associated harms of screening, and the benefits and harms of available treatments for small AAAs
(3.0-5.4 cm in diameter) identified through screening.
POPULATION This recommendation applies to asymptomatic adults 50 years or older.
Howeve
chunk text:
OBJECTIVE To update its 2014 recommendation, the USPSTF commissioned a review of the evidence on the effectiveness of 1-time and repeated screening for AAA, the associated harms of screening, and the benefits and harms of available treatments for small AAAs
(3.0-5.4 cm in diameter) identified through screening.
POPULATION This recommendation applies to asymptomatic adults 50 years or older.
However, the randomized trial evidence focuses almost entirely on men aged 65 to 75 years.
EVIDENCE ASSESS ...

------------------------------------------------------------------------------------------

==========================================================================================
Q10. What are the differences between open surgical repair and EVAR recommendations?
==========================================================================================
rank 1  score=0.7949
chunk_id: NICE_NG156__p40-40__c0122
document: Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
section: Repairing unruptured aneurysms
page: 40 (pages 40-40)
source_file: abdominal-aortic-aneurysm-diagnosis-and-management-pdf-66141843642565.pdf
recommendation metadata: none in this chunk
source excerpt: • has higher net costs and lower net benefits than open surgical repair or
• is substantially above the range NICE normally considers to be a cost-effective use of
NHS resources.
There is a small group of people who have abdominal copathology or other considerations that mean open surgical repair is unsuitable. Examples of copathologies include people who have internal scar-tissue from previous ab
chunk text:
• has higher net costs and lower net benefits than open surgical repair or
• is substantially above the range NICE normally considers to be a cost-effective use of
NHS resources.
There is a small group of people who have abdominal copathology or other considerations that mean open surgical repair is unsuitable. Examples of copathologies include people who have internal scar-tissue from previous abdominal surgery (a so-called hostile abdomen), people who have a single, fused kidney that is wrappe ...

------------------------------------------------------------------------------------------
rank 2  score=0.7869
chunk_id: NICE_NG156__p42-42__c0129
document: Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
section: EVAR and complex EVAR for specific subgroups of people
page: 42 (pages 42-42)
source_file: abdominal-aortic-aneurysm-diagnosis-and-management-pdf-66141843642565.pdf
recommendation metadata: none in this chunk
source excerpt: They show that, while outcomes from EVAR have improved over the last 15 years, outcomes from open surgical repair have also improved by roughly the same amount. This means the difference in outcomes between the two has remained fairly constant.
Registries like the National Vascular Registry can provide a useful snapshot of current practice, and the analyses that informed NICE's decision-making mad
chunk text:
They show that, while outcomes from EVAR have improved over the last 15 years, outcomes from open surgical repair have also improved by roughly the same amount. This means the difference in outcomes between the two has remained fairly constant.
Registries like the National Vascular Registry can provide a useful snapshot of current practice, and the analyses that informed NICE's decision-making made use of data from them. However, they are not designed to evaluate the comparative benefits and har ...

------------------------------------------------------------------------------------------
rank 3  score=0.7124
chunk_id: NICE_NG156__p40-40__c0123
document: Abdominal aortic aneurysm: diagnosis and management (NICE_NG156)
section: Repairing unruptured aneurysms
page: 40 (pages 40-40)
source_file: abdominal-aortic-aneurysm-diagnosis-and-management-pdf-66141843642565.pdf
recommendation metadata: none in this chunk
source excerpt: EVAR to people who could reasonably have open surgical repair.
Open surgical repair is contraindicated for some people with an unruptured AAA because of anaesthetic risks and/or medical comorbidities. For these people, the risk of their AAA rupturing if no repair is attempted has to be balanced against:
• the perioperative risks and long-term complications of EVAR
• the uncertainty around whether
chunk text:
EVAR to people who could reasonably have open surgical repair.
Open surgical repair is contraindicated for some people with an unruptured AAA because of anaesthetic risks and/or medical comorbidities. For these people, the risk of their AAA rupturing if no repair is attempted has to be balanced against:
• the perioperative risks and long-term complications of EVAR
• the uncertainty around whether they will benefit from EVAR
• the large costs of EVAR.
With all this in mind, it is clear that pract ...

------------------------------------------------------------------------------------------
rank 4  score=0.6999
chunk_id: ESVS_2024__p94-94__c1171
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: INFORMATION FOR PATIENTS
page: 94 (pages 94-94)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: EVAR vs. open repair did not change signiﬁcantly after DST implementation. The PROVE AAA cluster randomised trial in the USA (PReferences for Open vs. Endovascular repair of
AAA) reported that patients exposed to a decision aid were more likely to receive their preferred AAA repair type, with
285
chunk text:
EVAR vs. open repair did not change signiﬁcantly after DST implementation. The PROVE AAA cluster randomised trial in the USA (PReferences for Open vs. Endovascular repair of
AAA) reported that patients exposed to a decision aid were more likely to receive their preferred AAA repair type, with
285

------------------------------------------------------------------------------------------
rank 5  score=0.6982
chunk_id: ESVS_2024__p44-44__c0572
document: Editor's Choice -- European Society for Vascular Surgery (ESVS) 2024 Clinical Practice Guidelines on the Management of Abdominal Aorto-Iliac Artery Aneurysms&#x2606; (ESVS_2024)
section: EVAR SIZING AND PLANNING WORKSHEET
page: 44 (pages 44-44)
source_file: ESVS_2024_AAA_Guidelines.pdf
recommendation metadata: none in this chunk
source excerpt: Other factors of potential importance are improvements in pre-operative imaging and planning, the transition from general anaesthesia to percutaneous techniques under local anaesthesia, the rapid technical development of intra-operative imaging systems and the evolution of post-operative management. It is therefore necessary to include more recent observational and registry data in the overall eva
chunk text:
Other factors of potential importance are improvements in pre-operative imaging and planning, the transition from general anaesthesia to percutaneous techniques under local anaesthesia, the rapid technical development of intra-operative imaging systems and the evolution of post-operative management. It is therefore necessary to include more recent observational and registry data in the overall evaluation. Thus, despite data from multiple RCTs and meta-analysis, representing the highest LoE, the  ...

------------------------------------------------------------------------------------------

## Top-1 result per query

In [4]:
top1 = pd.DataFrame(
    [
        {
            "query_id": run["query_id"],
            "query": run["query"],
            "document_id": run["hits"][0]["document_id"],
            "section": run["hits"][0]["section"] or "<none>",
            "page": run["hits"][0]["page"],
            "chunk_id": run["hits"][0]["chunk_id"],
            "score": round(run["hits"][0]["similarity_score"], 4),
        }
        for run in query_runs
        if run["hits"]
    ]
)
display(top1)

assert len(query_runs) == len(cr.CLINICAL_QUERIES)
assert all(run["hits"] for run in query_runs), "every query must return chunks"
print(f"\n{len(query_runs)} clinical queries executed; all returned {TOP_K} chunks with metadata.")

   query_id                                                                             query  document_id                         section  page                   chunk_id   score
0         1         What are the recommendations for screening for abdominal aortic aneurysm?    ESVS_2024                Recommendation 9    19   ESVS_2024__p19-19__c0260  0.7281
1         2  What AAA diameter is generally associated with consideration of elective repair?    ESVS_2024       ABDOMINAL AORTIC ANEURYSM    26   ESVS_2024__p26-26__c0351  0.7688
2         3   What surveillance strategy is recommended for small abdominal aortic aneurysms?    ESVS_2024       ABDOMINAL AORTIC ANEURYSM    22   ESVS_2024__p22-22__c0297  0.7383
3         4                        What are the indications for endovascular aneurysm repair?    ESVS_2024                          <none>    83   ESVS_2024__p83-83__c1036  0.7132
4         5              What are the risk factors associated with abdominal aortic aneurysm?    ESVS_2024        INFORMATION FOR PATIENTS    95   ESVS_2024__p95-95__c1178  0.6718
5         6        What imaging modality is recommended for diagnosis or surveillance of AAA?    ESVS_2024       ABDOMINAL AORTIC ANEURYSM    21   ESVS_2024__p21-21__c0282  0.6702
6         7                                   What factors influence the risk of AAA rupture?  USPSTF_2019      Summary of Recommendations     2   USPSTF_2019__p2-2__c0016  0.6981
7         8          What are the recommendations for smoking cessation in patients with AAA?   NICE_NG156    Reducing the risk of rupture    11  NICE_NG156__p11-11__c0051  0.7535
8         9                   What are the recommendations for women regarding AAA screening?  USPSTF_2019                       Treatment     3   USPSTF_2019__p3-3__c0029  0.7064
9        10   What are the differences between open surgical repair and EVAR recommendations?   NICE_NG156  Repairing unruptured aneurysms    40  NICE_NG156__p40-40__c0122  0.7949

10 clinical queries executed; all returned 5 chunks with metadata.